# Generated by Django 2.2.8 on 2021-09-20 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0342_auto_20210914_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='editions',
        ),
        migrations.RemoveField(
            model_name='query',
            name='wos_collections',
        ),
        migrations.AddField(
            model_name='query',
            name='wos_collection',
            field=models.TextField(choices=[('all', 'All Databases'), ('core', 'Web of Science Core Collection'), ('biosis citation', 'BIOSIS Citation Index'), ('biosis previews', 'BIOSIS Previews'), ('kci', 'KCI-Korean Journal Database'), ('medline', 'MEDLINE'), ('russian', 'Russian Science Citation Index'), ('scielo', 'SciELO Citation Index')], default='core', null=True, verbose_name='WOS Collection'),
        ),
        migrations.AddField(
            model_name='query',
            name='wos_editions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), choices=[('all', 'All available'), ('SCI-EXPANDED', 'Science Citation Index Expanded (SCI-EXPANDED)--1900-present'), ('SSCI', 'Social Sciences Citation Index (SSCI)--1900-present'), ('AHCI', 'Arts & Humanities Citation Index (AHCI)--1975-present'), ('CPCI-S', 'Conference Proceedings Citation Index – Science (CPCI-S)--1990-present'), ('CPCI-SSH', 'Conference Proceedings Citation Index – Social Science & Humanities (CPCI-SSH)--1990-present'), ('ESCI', 'Emerging Sources Citation Index (ESCI)--2015-present')], default=['all'], null=True, size=None, verbose_name='WOS Editions'),
        ),
    ]
