# Generated by Django 2.2.8 on 2021-09-21 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0343_auto_20210920_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='credentials',
            field=models.NullBooleanField(verbose_name='Use credentials'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_file',
            field=models.FileField(null=True, upload_to='queries/', verbose_name='Query file(s)'),
        ),
        migrations.AlterField(
            model_name='query',
            name='wos_collection',
            field=models.TextField(choices=[('core', 'Web of Science Core Collection'), ('biosis citation', 'BIOSIS Citation Index'), ('biosis previews', 'BIOSIS Previews'), ('kci', 'KCI-Korean Journal Database'), ('medline', 'MEDLINE'), ('russian', 'Russian Science Citation Index'), ('scielo', 'SciELO Citation Index')], default='core', null=True, verbose_name='WOS Collection'),
        ),
        migrations.AlterField(
            model_name='query',
            name='wos_editions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), choices=[('SCI-EXPANDED', 'Science Citation Index Expanded (SCI-EXPANDED)'), ('SSCI', 'Social Sciences Citation Index (SSCI)'), ('AHCI', 'Arts & Humanities Citation Index (AHCI)'), ('CPCI-S', 'Conference Proceedings Citation Index – Science (CPCI-S)'), ('CPCI-SSH', 'Conference Proceedings Citation Index – Social Science & Humanities (CPCI-SSH)'), ('ESCI', 'Emerging Sources Citation Index (ESCI)')], default=list, null=True, size=None, verbose_name='WOS Editions'),
        ),
    ]
