# Generated by Django 2.2.8 on 2021-09-23 09:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0344_auto_20210921_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='wos_editions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, choices=[('SCI-EXPANDED', 'Science Citation Index Expanded (SCI-EXPANDED)'), ('SSCI', 'Social Sciences Citation Index (SSCI)'), ('AHCI', 'Arts & Humanities Citation Index (AHCI)'), ('CPCI-S', 'Conference Proceedings Citation Index – Science (CPCI-S)'), ('CPCI-SSH', 'Conference Proceedings Citation Index – Social Science & Humanities (CPCI-SSH)'), ('ESCI', 'Emerging Sources Citation Index (ESCI)')], default=list, null=True, size=None, verbose_name='WOS Editions'),
        ),
    ]
